id: 
name: GitOps.PullRequestIssueManagement.ComplianceReminders
description: Reminders to consider Compliance tasks and provide pointers to relevant documentation.
owner: 
resource: repository
disabled: false
where: 
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
    - description: '[21-10] Remind PR author to address release branches when making CI changes.'
      if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - targetsBranch:
          branch: dev
      - filesMatchPattern:
          pattern: '.*\.yml$'
          matchAny: true
      then:
      - addReply:
          reply: 'Since this PR is changing CI as it modifies YML files, please verify that you''ve addressed how this change should apply to release branches. Either: 
          
          - [ ] Link to equivalent PRs or Issues for each currently [supported branch](https://github.com/NuGet/Client.Engineering/blob/main/docs/HotSeat/NuGet.Client-Branches.md#supported-branches). 
          
          **or**
          
          - [ ] Explain in the PR description why this change doesn''t apply to release branches.'
    - description: '[21-20] Remind PR author to address accessibility and localizability when making UI changes.'
      if:
      - payloadType: Pull_Request
      - isAction:
          action: Opened
      - filesMatchPattern:
          pattern: '.*\.xaml$'
          matchAny: true
      then:
      - addReply:
          reply: 'This PR contains changes to XAML files. Verify that you''ve completed the following tasks: 
        
        - [ ] Complete [accessibility testing](https://github.com/NuGet/NuGet.Client/blob/dev/docs/ui-guidelines.md#accessibility-testing). 
        
        - [ ] Complete [localizability testing](https://github.com/NuGet/NuGet.Client/blob/dev/docs/ui-guidelines.md#localizability-testing).'