<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <DebuggerFlavor>VsixDebugger</DebuggerFlavor>
  </PropertyGroup>

  <PropertyGroup>
    <!-- When the PackageManifest/Installation/Experimental attribute in source.extension.vsixmanifest is true,
         installing the VSIX will override without removing an already existing extension.
         This is only desirable when the VSIX is built within VS, where the user presumably expects F5 to work. -->
    <IsExperimental Condition="'$(IsExperimental)'=='' and '$(BuildingInsideVisualStudio)' == 'true'">true</IsExperimental>
    <IsExperimental Condition="'$(IsExperimental)'==''">false</IsExperimental>
  </PropertyGroup>

  <PropertyGroup>
    <!-- When the PackageManifest/Installation/SystemComponent attribute in source.extension.vsixmanifest is true,
         the extension will NOT appear in the Extension Manager when installed.
         We typically want to NOT appear, since we're in-box.
         But we want it to appear iff the extension is built in per-user deployment mode so it can be uninstalled,
         allowing the in-box copy to re-assert itself.
     -->
    <IsSystemComponent>true</IsSystemComponent>
    <IsSystemComponent Condition="'$(IsExperimental)' == 'true'">false</IsSystemComponent>
  </PropertyGroup>

  <!-- These targets expose the msbuild properties (that we made up) to the source.extension.vsixmanifest files,
       allowing those xml attributes to vary based on conditions that msbuild is aware of. -->
  <Target Name="GetIsExperimental" Outputs="$(IsExperimental)" />
  <Target Name="GetIsSystemComponent" Outputs="$(IsSystemComponent)" />
</Project>
