<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TargetFrameworksUnitTest)</TargetFrameworks>
    <Description>Unit tests for NuGet.Repo.Analyzers.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\Analyzers\NuGet.Repo.Analyzers\NuGet.Repo.Analyzers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
  </ItemGroup>

</Project>
