// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.ActivityCorrelationIdTests.AsyncCallC(System.TimeSpan)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.ActivityCorrelationIdTests.ChangeActivityCorrelationId~System.String")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.ActivityCorrelationIdTests.ChangeActivityCorrelationIdAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.CultureUtilityTests.GetResourceOutput(System.Action)~NuGet.Common.Test.CultureUtilityTests.LocalizedOutput")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.DirectoryUtilityTests.StatPermissions(System.String)~System.String")]
[assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.KeyedLockTests.Dispose")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.PathResolverTests.PerformWildcardSearch_WithDirectory_FindsNoMatchingFiles(System.String)")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.PathResolverTests.PerformWildcardSearch_WithFileName_FindsNoMatchingFile")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.PathResolverTests.PerformWildcardSearch_WithFileNamePattern_FindsNoMatchingFile")]
[assembly: SuppressMessage("Performance", "CA1826:Do not use Enumerable methods on indexable collections", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.RestoreLogMessageTests.RestoreLogMessage_TestConstructorWithTargetGraph(NuGet.Common.LogLevel,NuGet.Common.NuGetLogCode,System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1806:Do not ignore method results", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.RestoreLogMessageTests.RestoreLogMessage_TestCreateError(NuGet.Common.NuGetLogCode,System.String,System.String,System.String[])")]
[assembly: SuppressMessage("Performance", "CA1806:Do not ignore method results", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.RestoreLogMessageTests.RestoreLogMessage_TestCreateWarning(NuGet.Common.NuGetLogCode,System.String,System.String,System.String[])")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.SynchronizationTests.ReleaseLock(NuGet.Common.Test.SynchronizationTests.SyncdRunResult)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Common.Test.SynchronizationTests.WaitForLockToEngage(NuGet.Common.Test.SynchronizationTests.SyncdRunResult)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Core.FuncTest.ActivityCorrelationIdFuncTests.AsyncCallC(System.TimeSpan)~System.Threading.Tasks.Task{System.String}")]
[assembly: SuppressMessage("Reliability", "CA2016:Forward the 'CancellationToken' parameter to methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Core.FuncTest.ConcurrencyUtilitiesTests.ConcurrencyUtilities_LockAllCasings~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2016:Forward the 'CancellationToken' parameter to methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Core.FuncTest.ConcurrencyUtilitiesTests.ConcurrencyUtilities_LockStress~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Reliability", "CA2016:Forward the 'CancellationToken' parameter to methods", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.Core.FuncTest.ConcurrencyUtilitiesTests.ConcurrencyUtilities_NormalizePaths~System.Threading.Tasks.Task")]
