//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.ProjectModel {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Strings() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGet.ProjectModel.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid dependency target value &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidDependencyTarget {
            get {
                return ResourceManager.GetString("InvalidDependencyTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error loading lock file &apos;{0}&apos; : {1}.
        /// </summary>
        internal static string Log_ErrorReadingLockFile {
            get {
                return ResourceManager.GetString("Log_ErrorReadingLockFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error reading &apos;{0}&apos; : {1}.
        /// </summary>
        internal static string Log_ErrorReadingProjectJson {
            get {
                return ResourceManager.GetString("Log_ErrorReadingProjectJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error reading &apos;{0}&apos; at line {1} column {2} : {3}.
        /// </summary>
        internal static string Log_ErrorReadingProjectJsonWithLocation {
            get {
                return ResourceManager.GetString("Log_ErrorReadingProjectJsonWithLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Imports contains an invalid framework: &apos;{0}&apos; in &apos;{1}&apos;..
        /// </summary>
        internal static string Log_InvalidImportFramework {
            get {
                return ResourceManager.GetString("Log_InvalidImportFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package dependencies must specify a version range..
        /// </summary>
        internal static string MissingVersionProperty {
            get {
                return ResourceManager.GetString("MissingVersionProperty", resourceCulture);
            }
        }
    }
}
