//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.PackageManagement {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Strings() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGet.PackageManagement.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Another NuGetProject with the same name &apos;{0}&apos; exists in solution.
        /// </summary>
        public static string AnotherNuGetProjectWithSameNameExistsInSolution {
            get {
                return ResourceManager.GetString("AnotherNuGetProjectWithSameNameExistsInSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Attempting to gather dependency information for package &apos;{0}&apos; with respect to project &apos;{1}&apos;, targeting &apos;{2}&apos;.
        /// </summary>
        public static string AttemptingToGatherDependencyInfo {
            get {
                return ResourceManager.GetString("AttemptingToGatherDependencyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Attempting to gather dependency information for multiple packages with respect to project &apos;{0}&apos;, targeting &apos;{1}&apos;.
        /// </summary>
        public static string AttemptingToGatherDependencyInfoForMultiplePackages {
            get {
                return ResourceManager.GetString("AttemptingToGatherDependencyInfoForMultiplePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Attempting to resolve dependencies for package &apos;{0}&apos; with DependencyBehavior &apos;{1}&apos;.
        /// </summary>
        public static string AttemptingToResolveDependencies {
            get {
                return ResourceManager.GetString("AttemptingToResolveDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Attempting to resolve dependencies for multiple packages..
        /// </summary>
        public static string AttemptingToResolveDependenciesForMultiplePackages {
            get {
                return ResourceManager.GetString("AttemptingToResolveDependenciesForMultiplePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package restore failed for &apos;{0}&apos;..
        /// </summary>
        public static string BuildIntegratedPackageRestoreFailed {
            get {
                return ResourceManager.GetString("BuildIntegratedPackageRestoreFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Restoring packages for &apos;{0}&apos;..
        /// </summary>
        public static string BuildIntegratedPackageRestoreStarted {
            get {
                return ResourceManager.GetString("BuildIntegratedPackageRestoreStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package restore completed successfully for &apos;{0}&apos;..
        /// </summary>
        public static string BuildIntegratedPackageRestoreSucceeded {
            get {
                return ResourceManager.GetString("BuildIntegratedPackageRestoreSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot download packages from &apos;{0}&apos;..
        /// </summary>
        public static string DownloadResourceNotFound {
            get {
                return ResourceManager.GetString("DownloadResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package stream for &apos;{0}&apos; cannot be found at &apos;{1}&apos;..
        /// </summary>
        public static string DownloadStreamNotAvailable {
            get {
                return ResourceManager.GetString("DownloadStreamNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to find package &apos;{0}&apos; at source &apos;{1}&apos;..
        /// </summary>
        public static string Exception_PackageNotFound {
            get {
                return ResourceManager.GetString("Exception_PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Exception Type.
        /// </summary>
        public static string ExceptionType {
            get {
                return ResourceManager.GetString("ExceptionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Exception &apos;{0}&apos; thrown when trying to add source &apos;{1}&apos;. Please verify all your online package sources are available..
        /// </summary>
        public static string ExceptionWhenTryingToAddSource {
            get {
                return ResourceManager.GetString("ExceptionWhenTryingToAddSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Found package &apos;{0} {1}&apos; in &apos;{2}&apos;..
        /// </summary>
        public static string FoundPackageInPackagesFolder {
            get {
                return ResourceManager.GetString("FoundPackageInPackagesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Gathering dependency information took {0}.
        /// </summary>
        public static string GatherTotalTime {
            get {
                return ResourceManager.GetString("GatherTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Installed package &apos;{0}&apos; to project.
        /// </summary>
        public static string InstalledPackage {
            get {
                return ResourceManager.GetString("InstalledPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Installing package &apos;{0}&apos; to project.
        /// </summary>
        public static string InstallingPackage {
            get {
                return ResourceManager.GetString("InstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; cannot be called on a NullSettings. This may be caused on account of insufficient permissions to read or write to &apos;%AppData%\NuGet\NuGet.config&apos;.
        /// </summary>
        public static string InvalidNullSettingsOperation {
            get {
                return ResourceManager.GetString("InvalidNullSettingsOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to When updating multiple packages, dependency behavior has to be DependencyBehavior.Highest.
        /// </summary>
        public static string MultiplePackageInstallOrUpdateHasToBeAnUpdate {
            get {
                return ResourceManager.GetString("MultiplePackageInstallOrUpdateHasToBeAnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; has multiple package types, which is not supported..
        /// </summary>
        public static string MultiplePackageTypesNotSupported {
            get {
                return ResourceManager.GetString("MultiplePackageTypesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Already referencing a newer version of &apos;{0}&apos;...
        /// </summary>
        public static string NewerVersionAlreadyReferenced {
            get {
                return ResourceManager.GetString("NewerVersionAlreadyReferenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No latest version found for &apos;{0}&apos; for the given source repositories and resolution context.
        /// </summary>
        public static string NoLatestVersionFound {
            get {
                return ResourceManager.GetString("NoLatestVersionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No NuGetProject is available with specified name &apos;{0}&apos;.
        /// </summary>
        public static string NoNuGetProjectWithSpecifiedName {
            get {
                return ResourceManager.GetString("NoNuGetProjectWithSpecifiedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No packages were found in packages.config for project &apos;{0}&apos;..
        /// </summary>
        public static string NoPackagesInProject {
            get {
                return ResourceManager.GetString("NoPackagesInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to There are no new updates available..
        /// </summary>
        public static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Executing nuget actions took {0}.
        /// </summary>
        public static string NugetActionsTotalTime {
            get {
                return ResourceManager.GetString("NugetActionsTotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to NuGetProject does not have &apos;Name&apos; set in metadata. It should be set and it should be unique.
        /// </summary>
        public static string NuGetProjectDoesNotHaveName {
            get {
                return ResourceManager.GetString("NuGetProjectDoesNotHaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to One or more packages not found.
        /// </summary>
        public static string OneOrMorePackagesNotFound {
            get {
                return ResourceManager.GetString("OneOrMorePackagesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Getting package &apos;{0}&apos; from source &apos;{1}&apos; was cancelled..
        /// </summary>
        public static string PackageCancelledFromSource {
            get {
                return ResourceManager.GetString("PackageCancelledFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; could not be installed.
        /// </summary>
        public static string PackageCouldNotBeInstalled {
            get {
                return ResourceManager.GetString("PackageCouldNotBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to uninstall &apos;{0}&apos; because &apos;{1}&apos; depends on it..
        /// </summary>
        public static string PackageHasDependent {
            get {
                return ResourceManager.GetString("PackageHasDependent", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to uninstall &apos;{0}&apos; because &apos;{1}&apos; depend on it..
        /// </summary>
        public static string PackageHasDependents {
            get {
                return ResourceManager.GetString("PackageHasDependents", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; is not found.
        /// </summary>
        public static string PackageNotFound {
            get {
                return ResourceManager.GetString("PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; is not found in the following primary source(s): &apos;{1}&apos;. Please verify all your online package sources are available (OR) package id, version are specified correctly..
        /// </summary>
        public static string PackageNotFoundInPrimarySources {
            get {
                return ResourceManager.GetString("PackageNotFoundInPrimarySources", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; is not found on source &apos;{1}&apos;..
        /// </summary>
        public static string PackageNotFoundOnSource {
            get {
                return ResourceManager.GetString("PackageNotFoundOnSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to resolve &apos;{0}&apos;. An additional constraint &apos;{1}&apos; defined in {2} prevents this operation..
        /// </summary>
        public static string PackagesConfigAllowedVersionConflict {
            get {
                return ResourceManager.GetString("PackagesConfigAllowedVersionConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Applying constraint &apos;{0}&apos; defined in &apos;{1}&apos;..
        /// </summary>
        public static string PackagesConfigAllowedVersions {
            get {
                return ResourceManager.GetString("PackagesConfigAllowedVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Packages could not be installed.
        /// </summary>
        public static string PackagesCouldNotBeInstalled {
            get {
                return ResourceManager.GetString("PackagesCouldNotBeInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; to be uninstalled could not be found in project &apos;{1}&apos;.
        /// </summary>
        public static string PackageToBeUninstalledCouldNotBeFound {
            get {
                return ResourceManager.GetString("PackageToBeUninstalledCouldNotBeFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Parameter cannot be zero or negative.
        /// </summary>
        public static string ParameterCannotBeZeroOrNegative {
            get {
                return ResourceManager.GetString("ParameterCannotBeZeroOrNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Resolution was successful but resulted in no action.
        /// </summary>
        public static string ResolutionSuccessfulNoAction {
            get {
                return ResourceManager.GetString("ResolutionSuccessfulNoAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Resolved actions to install package &apos;{0}&apos;.
        /// </summary>
        public static string ResolvedActionsToInstallPackage {
            get {
                return ResourceManager.GetString("ResolvedActionsToInstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Resolved actions to uninstall package &apos;{0}&apos;.
        /// </summary>
        public static string ResolvedActionsToUninstallPackage {
            get {
                return ResourceManager.GetString("ResolvedActionsToUninstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Resolving actions install multiple packages.
        /// </summary>
        public static string ResolvingActionsToInstallOrUpdateMultiplePackages {
            get {
                return ResourceManager.GetString("ResolvingActionsToInstallOrUpdateMultiplePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Resolving actions to install package &apos;{0}&apos;.
        /// </summary>
        public static string ResolvingActionsToInstallPackage {
            get {
                return ResourceManager.GetString("ResolvingActionsToInstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Resolving actions to uninstall package &apos;{0}&apos;.
        /// </summary>
        public static string ResolvingActionsToUninstallPackage {
            get {
                return ResourceManager.GetString("ResolvingActionsToUninstallPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package restore failed. Rolling back package changes for &apos;{0}&apos;..
        /// </summary>
        public static string RestoreFailedRollingBack {
            get {
                return ResourceManager.GetString("RestoreFailedRollingBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Restoring NuGet package {0}..
        /// </summary>
        public static string RestoringPackage {
            get {
                return ResourceManager.GetString("RestoringPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Retrieving package &apos;{0} {1}&apos; from &apos;{2}&apos;..
        /// </summary>
        public static string RetrievingPackageStart {
            get {
                return ResourceManager.GetString("RetrievingPackageStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Solution is not opened or not saved. Please ensure you have an open and saved solution..
        /// </summary>
        public static string SolutionDirectoryNotAvailable {
            get {
                return ResourceManager.GetString("SolutionDirectoryNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Uninstall is not supported when SolutionManager is not available.
        /// </summary>
        public static string SolutionManagerNotAvailableForUninstall {
            get {
                return ResourceManager.GetString("SolutionManagerNotAvailableForUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Successfully installed &apos;{0}&apos; to {1}.
        /// </summary>
        public static string SuccessfullyInstalled {
            get {
                return ResourceManager.GetString("SuccessfullyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Successfully uninstalled &apos;{0}&apos; from {1}.
        /// </summary>
        public static string SuccessfullyUninstalled {
            get {
                return ResourceManager.GetString("SuccessfullyUninstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to gather dependency information for package &apos;{0}&apos;.
        /// </summary>
        public static string UnableToGatherDependencyInfo {
            get {
                return ResourceManager.GetString("UnableToGatherDependencyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to gather dependency information for multiple packages.
        /// </summary>
        public static string UnableToGatherDependencyInfoForMultiplePackages {
            get {
                return ResourceManager.GetString("UnableToGatherDependencyInfoForMultiplePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to gather package &apos;{0}&apos; from source &apos;{1}&apos;. Please verify all your online package sources are available. .
        /// </summary>
        public static string UnableToGatherPackageFromSource {
            get {
                return ResourceManager.GetString("UnableToGatherPackageFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to resolve dependencies for package &apos;{0}&apos; with DependencyBehavior &apos;{1}&apos;.
        /// </summary>
        public static string UnableToResolveDependencyInfo {
            get {
                return ResourceManager.GetString("UnableToResolveDependencyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to resolve dependencies for multiple packages.
        /// </summary>
        public static string UnableToResolveDependencyInfoForMultiplePackages {
            get {
                return ResourceManager.GetString("UnableToResolveDependencyInfoForMultiplePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to find package &apos;{0}&apos;.
        /// </summary>
        public static string UnknownPackage {
            get {
                return ResourceManager.GetString("UnknownPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to find version &apos;{1}&apos; of package &apos;{0}&apos;..
        /// </summary>
        public static string UnknownPackageSpecificVersion {
            get {
                return ResourceManager.GetString("UnknownPackageSpecificVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Source &apos;{0}&apos; not found. Please provide an HTTP or local source..
        /// </summary>
        public static string UnknownSource {
            get {
                return ResourceManager.GetString("UnknownSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unsupported type of source &apos;{0}&apos;. Please provide an HTTP or local source..
        /// </summary>
        public static string UnknownSourceType {
            get {
                return ResourceManager.GetString("UnknownSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to find package &apos;{0}&apos; at source &apos;{1}&apos;. Source not found..
        /// </summary>
        public static string UnknownSourceWithId {
            get {
                return ResourceManager.GetString("UnknownSourceWithId", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; uses features that are not supported by the current version of NuGet. To upgrade NuGet, see http://docs.nuget.org/consume/installing-nuget..
        /// </summary>
        public static string UnsupportedPackageFeature {
            get {
                return ResourceManager.GetString("UnsupportedPackageFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; has a package type &apos;{1}&apos; that is not supported by project &apos;{2}&apos;..
        /// </summary>
        public static string UnsupportedPackageType {
            get {
                return ResourceManager.GetString("UnsupportedPackageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error finding repository for &apos;{0}&apos;: {1}.
        /// </summary>
        public static string Warning_ErrorFindingRepository {
            get {
                return ResourceManager.GetString("Warning_ErrorFindingRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Install failed. Rolling back....
        /// </summary>
        public static string Warning_RollingBack {
            get {
                return ResourceManager.GetString("Warning_RollingBack", resourceCulture);
            }
        }
    }
}
