<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>sdkCurrent;sdkNext</TargetFrameworks>
    <Description>Integration tests for NuGet-powered dotnet CLI commands such as pack/restore/list package and dotnet nuget.</Description>
    <TargetFrameworkIdentifier>.NETCoreApp</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v10.0</TargetFrameworkVersion>
    <TargetFrameworkMoniker>.NETCoreApp,Version=v10.0</TargetFrameworkMoniker>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'sdkCurrent'">
    <DefineConstants>$(DefineConstants);SDK_CURRENT</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'sdkNext'">
    <DefineConstants>$(DefineConstants);SDK_NEXT</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="compiler\resources\*" />
    <EmbeddedResource Include="compiler\resources\*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NuGet.XPlat.FuncTest\NuGet.XPlat.FuncTest.csproj" />
    <ProjectReference Include="..\..\TestUtilities\Test.Utility\Test.Utility.csproj" />
    <ProjectReference Include="..\..\..\src\NuGet.Core\NuGet.Build.Tasks.Pack\NuGet.Build.Tasks.Pack.csproj" />
    <ProjectReference Include="..\..\..\src\NuGet.Core\NuGet.Build.Tasks.Console\NuGet.Build.Tasks.Console.csproj" />
    <ProjectReference Include="..\..\..\src\NuGet.Core\Microsoft.Build.NuGetSdkResolver\Microsoft.Build.NuGetSdkResolver.csproj" />
  </ItemGroup>
</Project>
