// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.DotnetAddPackageTests.AddPkg_V3LocalSourceFeed_WithDefaultSolutiuonSource_NoVersionSpecified_Success~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.DotnetAddPackageTests.AddPkg_V3LocalSourceFeed_WithRelativePath_NoVersionSpecified_Success~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.DotnetAddPackageTests.AddPkg_V3LocalSourceFeed_WithRelativePath_VersionSpecified_Success~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Usage", "xUnit1004:Test methods should not be skipped", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.DotnetListPackageTests.DotnetListPackage_VerbositySwitchTogglesHttpVisibility(System.String,System.Boolean)")]
[assembly: SuppressMessage("Usage", "xUnit1004:Test methods should not be skipped", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.DotnetSourcesTests.TestVerbosityQuiet_DoesNotShowInfoMessages")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.MockServer.GetPushedPackage(System.Net.HttpListenerRequest)~System.Byte[]")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.MockServer.SetResponseNotFound(System.Net.HttpListenerResponse)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.MsbuildIntegrationTestFixture.Build(NuGet.Test.Utility.TestDirectoryBuilder)~NuGet.Test.Utility.TestDirectory")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.MsbuildIntegrationTestFixture.CreateDotnetToolProject(System.String,System.String,System.String,System.String,System.String,System.Collections.Generic.IList{NuGet.Packaging.Core.PackageIdentity},System.Int32)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.MsbuildIntegrationTestFixture.CreateTestDirectory~NuGet.Test.Utility.TestDirectory")]
[assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.MsbuildIntegrationTestFixture.Dispose")]
[assembly: SuppressMessage("Usage", "xUnit1004:Test methods should not be skipped", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.PackCommand_Deterministic_MultiplePackInvocations_CreateIdenticalPackages")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.PackCommand_MultipleFrameworks_GeneratesPackageOnBuild(System.String)")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.PackCommand_PackProject_AddsReferenceAsFrameworkAssemblyReference(System.String,System.Boolean,System.String,System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.PackCommand_PackProject_ExactVersionOverrideProjectRefVersionInMsbuild(System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.PackCommand_PackProject_GetPackageVersionDependsOnWorks(System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.PackCommand_PackProject_GetsProjectRefVersionFromMsbuild(System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.PackCommand_PackProject_GlobbingPathsPacksContentCorrectly(System.String,System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.PackCommand_PackProject_OutputsBuildActionForContentFiles(System.String,System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.PackCommand_PackProject_OutputsContentFilesInNuspecForMultipleFrameworks(System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.PackCommand_PackProject_OutputsContentFilesInNuspecForSingleFramework(System.String,System.String,System.String)")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.PackCommand_PackProject_PacksFrameworkReferences(System.String,System.String,System.String,System.String,System.String)")]
[assembly: SuppressMessage("Usage", "xUnit1004:Test methods should not be skipped", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.PackCommand_PackProjectWithCentralTransitiveDependencies")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.ValidatePackIcon(NuGet.Test.Utility.ProjectFileBuilder)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.PackCommandTests.ValidatePackReadme(NuGet.Test.Utility.ProjectFileBuilder)")]
[assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<Pending>", Scope = "member", Target = "~M:Dotnet.Integration.Test.SignCommandTestFixture.Dispose")]
