//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NuGet.ProjectManagement {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Strings() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NuGet.ProjectManagement.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Added package &apos;{0}&apos; to folder &apos;{1}&apos;.
        /// </summary>
        public static string AddedPackageToFolder {
            get {
                return ResourceManager.GetString("AddedPackageToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Added package &apos;{0}&apos; to folder &apos;{1}&apos; from source &apos;{2}&apos;.
        /// </summary>
        public static string AddedPackageToFolderFromSource {
            get {
                return ResourceManager.GetString("AddedPackageToFolderFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Added package &apos;{0}&apos; to project &apos;{1}&apos;.
        /// </summary>
        public static string AddedPackageToMSBuildProject {
            get {
                return ResourceManager.GetString("AddedPackageToMSBuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Added package &apos;{0}&apos; to &apos;{1}&apos;.
        /// </summary>
        public static string AddedPackageToPackagesConfig {
            get {
                return ResourceManager.GetString("AddedPackageToPackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Adding package &apos;{0}&apos; to folder &apos;{1}&apos;.
        /// </summary>
        public static string AddingPackageToFolder {
            get {
                return ResourceManager.GetString("AddingPackageToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Adding package &apos;{0}&apos; to project &apos;{1}&apos;.
        /// </summary>
        public static string AddingPackageToMSBuildProject {
            get {
                return ResourceManager.GetString("AddingPackageToMSBuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Adding package &apos;{0}&apos;, which only has dependencies, to project &apos;{1}&apos;..
        /// </summary>
        public static string AddingPackageWithOnlyDependencies {
            get {
                return ResourceManager.GetString("AddingPackageWithOnlyDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Adding package &apos;{0}&apos;, which only has tools group, to project &apos;{1}&apos;.
        /// </summary>
        public static string AddingPackageWithOnlyToolsGroup {
            get {
                return ResourceManager.GetString("AddingPackageWithOnlyToolsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Argument cannot be null or empty.
        /// </summary>
        public static string Argument_Cannot_Be_Null_Or_Empty {
            get {
                return ResourceManager.GetString("Argument_Cannot_Be_Null_Or_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value must be greater than or equal to {0}.
        /// </summary>
        public static string Argument_Must_Be_GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("Argument_Must_Be_GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Content files should not be target framework specific, whereas, &apos;{0}&apos; is.
        /// </summary>
        public static string ContentFilesShouldNotBeTargetFrameworkSpecific {
            get {
                return ResourceManager.GetString("ContentFilesShouldNotBeTargetFrameworkSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Added file &apos;{0}&apos;..
        /// </summary>
        public static string Debug_AddedFile {
            get {
                return ResourceManager.GetString("Debug_AddedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Added file &apos;{0}&apos; to folder &apos;{1}&apos;..
        /// </summary>
        public static string Debug_AddedFileToFolder {
            get {
                return ResourceManager.GetString("Debug_AddedFileToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Removed file &apos;{0}&apos;..
        /// </summary>
        public static string Debug_RemovedFile {
            get {
                return ResourceManager.GetString("Debug_RemovedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Removed file &apos;{0}&apos; from folder &apos;{1}&apos;..
        /// </summary>
        public static string Debug_RemovedFileFromFolder {
            get {
                return ResourceManager.GetString("Debug_RemovedFileFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Removed folder &apos;{0}&apos;..
        /// </summary>
        public static string Debug_RemovedFolder {
            get {
                return ResourceManager.GetString("Debug_RemovedFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &gt;&gt; {0} are being added from &apos;{1}&apos;{2}.
        /// </summary>
        public static string Debug_TargetFrameworkInfo {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Assembly references.
        /// </summary>
        public static string Debug_TargetFrameworkInfo_AssemblyReferences {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_AssemblyReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Build files.
        /// </summary>
        public static string Debug_TargetFrameworkInfo_BuildFiles {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_BuildFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Content files.
        /// </summary>
        public static string Debug_TargetFrameworkInfo_ContentFiles {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_ContentFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to (not framework-specific).
        /// </summary>
        public static string Debug_TargetFrameworkInfo_NotFrameworkSpecific {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_NotFrameworkSpecific", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &gt;&gt; PowerShell scripts are being executed from &apos;{0}&apos;{1}.
        /// </summary>
        public static string Debug_TargetFrameworkInfo_PowershellScripts {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfo_PowershellScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to For adding package &apos;{0}&apos; to project &apos;{1}&apos; that targets &apos;{2}&apos;..
        /// </summary>
        public static string Debug_TargetFrameworkInfoPrefix {
            get {
                return ResourceManager.GetString("Debug_TargetFrameworkInfoPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Dependency &apos;{0}&apos; has invalid version specification..
        /// </summary>
        public static string DependencyDoesNotHaveValidVersion {
            get {
                return ResourceManager.GetString("DependencyDoesNotHaveValidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while reading file &apos;{0}&apos;: {1}.
        /// </summary>
        public static string ErrorLoadingPackagesConfig {
            get {
                return ResourceManager.GetString("ErrorLoadingPackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while writing file &apos;{0}&apos;: {1}.
        /// </summary>
        public static string ErrorWritingPackagesConfig {
            get {
                return ResourceManager.GetString("ErrorWritingPackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to File &apos;{0}&apos; already exists in project &apos;{1}&apos;. Do you want to overwrite it?.
        /// </summary>
        public static string FileConflictMessage {
            get {
                return ResourceManager.GetString("FileConflictMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Overwriting existing file &apos;{0}&apos;...
        /// </summary>
        public static string Info_OverwritingExistingFile {
            get {
                return ResourceManager.GetString("Info_OverwritingExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Unable to determine the project name for &apos;{0}&apos;..
        /// </summary>
        public static string InvalidProjectName {
            get {
                return ResourceManager.GetString("InvalidProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid!! Could not find a folder under artifact type &apos;{0}&apos;, so cannot request for artifacts specific to target framework &apos;{1}&apos;.
        /// </summary>
        public static string NoFolderSpecificToTargetFxFound {
            get {
                return ResourceManager.GetString("NoFolderSpecificToTargetFxFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; already exists in folder &apos;{1}&apos;.
        /// </summary>
        public static string PackageAlreadyExistsInFolder {
            get {
                return ResourceManager.GetString("PackageAlreadyExistsInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; already exists in &apos;{1}&apos;.
        /// </summary>
        public static string PackageAlreadyExistsInPackagesConfig {
            get {
                return ResourceManager.GetString("PackageAlreadyExistsInPackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; already exists in project &apos;{1}&apos;.
        /// </summary>
        public static string PackageAlreadyExistsInProject {
            get {
                return ResourceManager.GetString("PackageAlreadyExistsInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; does not exist in folder &apos;{1}&apos;.
        /// </summary>
        public static string PackageDoesNotExistInFolder {
            get {
                return ResourceManager.GetString("PackageDoesNotExistInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; does not exist in project &apos;{1}&apos;.
        /// </summary>
        public static string PackageDoesNotExistInProject {
            get {
                return ResourceManager.GetString("PackageDoesNotExistInProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package &apos;{0}&apos; does not exists in &apos;{1}&apos;.
        /// </summary>
        public static string PackageDoesNotExisttInPackagesConfig {
            get {
                return ResourceManager.GetString("PackageDoesNotExisttInPackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Package stream should be seekable.
        /// </summary>
        public static string PackageStreamShouldBeSeekable {
            get {
                return ResourceManager.GetString("PackageStreamShouldBeSeekable", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Removed package &apos;{0}&apos; from folder &apos;{1}&apos;.
        /// </summary>
        public static string RemovedPackageFromFolder {
            get {
                return ResourceManager.GetString("RemovedPackageFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Removed package &apos;{0}&apos; from project &apos;{1}&apos;.
        /// </summary>
        public static string RemovedPackageFromMSBuildProject {
            get {
                return ResourceManager.GetString("RemovedPackageFromMSBuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Removed package &apos;{0}&apos; from &apos;{1}&apos;.
        /// </summary>
        public static string RemovedPackageFromPackagesConfig {
            get {
                return ResourceManager.GetString("RemovedPackageFromPackagesConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Removing package &apos;{0}&apos; from folder &apos;{1}&apos;.
        /// </summary>
        public static string RemovingPackageFromFolder {
            get {
                return ResourceManager.GetString("RemovingPackageFromFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Removing package &apos;{0}&apos; from project &apos;{1}&apos;.
        /// </summary>
        public static string RemovingPackageFromMSBuildProject {
            get {
                return ResourceManager.GetString("RemovingPackageFromMSBuildProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Solution directory &apos;{0}&apos; must be a rooted path..
        /// </summary>
        public static string SolutionDirectoryMustBeRooted {
            get {
                return ResourceManager.GetString("SolutionDirectoryMustBeRooted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The replacement token &apos;{0}&apos; has no value.
        /// </summary>
        public static string TokenHasNoValue {
            get {
                return ResourceManager.GetString("TokenHasNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Could not install package &apos;{0}&apos;. You are trying to install this package into a project that targets &apos;{1}&apos;, but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author..
        /// </summary>
        public static string UnableToFindCompatibleItems {
            get {
                return ResourceManager.GetString("UnableToFindCompatibleItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Directory &apos;{0}&apos; is not empty. Skipping....
        /// </summary>
        public static string Warning_DirectoryNotEmpty {
            get {
                return ResourceManager.GetString("Warning_DirectoryNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; already exists. Skipping....
        /// </summary>
        public static string Warning_FileAlreadyExists {
            get {
                return ResourceManager.GetString("Warning_FileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Skipping &apos;{0}&apos; because it was modified..
        /// </summary>
        public static string Warning_FileModified {
            get {
                return ResourceManager.GetString("Warning_FileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to An error occurred while applying transformation to &apos;{0}&apos; in project &apos;{1}&apos;.
        /// </summary>
        public static string XdtError {
            get {
                return ResourceManager.GetString("XdtError", resourceCulture);
            }
        }
    }
}
