// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// Do not manually edit this autogenerated file:
// instead modify the neighboring .tt file (text template) and/or NuGet.CommandLine.Xplat\Commands\Commands.xml (data file),
// then re-execute the text template via "run custom tool" on VS context menu for .tt file, or via dotnet-t4 global tool.

using System;
using Microsoft.Extensions.CommandLineUtils;
using NuGet.Common;

namespace NuGet.CommandLine.XPlat
{
    internal static class CommandParsers
    {
        public static void Register(CommandLineApplication app, Func<ILogger> getLogger)
        {
            AddVerbParser.Register(app, getLogger);
            DisableVerbParser.Register(app, getLogger);
            EnableVerbParser.Register(app, getLogger);
            ListVerbParser.Register(app, getLogger);
            RemoveVerbParser.Register(app, getLogger);
            UpdateVerbParser.Register(app, getLogger);
            ConfigVerbParser.Register(app, getLogger);
        }
    }
}
