// <auto-generated />
namespace NuGet.DependencyResolver.Core
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Strings
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("NuGet.DependencyResolver.Core.Strings", typeof(Strings).GetTypeInfo().Assembly);

        /// <summary>
        /// Unable to find a version of package '{0}' that is compatible with version constraint '{1}'.
        /// </summary>
        internal static string Error_FailedToResolveConflicts
        {
            get { return GetString("Error_FailedToResolveConflicts"); }
        }

        /// <summary>
        /// Unable to find a version of package '{0}' that is compatible with version constraint '{1}'.
        /// </summary>
        internal static string FormatError_FailedToResolveConflicts(object p0, object p1)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("Error_FailedToResolveConflicts"), p0, p1);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
