parameters:
  - name: dependsOn
    type: object
  - name: bootstrapperUrl
    type: string
  - name: runSettingsURI
    type: string
  - name: condition
    type: string
  - name: variables
    type: object
  - name: testExecutionJobTimeoutInMinutes
    type: number
  - name: testDeploymentCleanupMode
    type: string
    default: OnSuccess
    values:
      - Always
      - Never
      - OnSuccess

stages:
  - template: stages/cloudtest/visual-studio/single-runsettings.yml@DartLabTemplates
    parameters:
      name: VS_Apex_Tests
      displayName: Apex Tests On Windows
      condition: ${{parameters.condition}}
      dependsOn: ${{parameters.dependsOn}}
      variables:
        - ${{if gt(length(parameters.variables), 0)}}:
          - ${{parameters.variables}}
      owner: nugetclienteng
      testMachineLab: "VSIDE"
      runSettingsURI: ${{parameters.runSettingsURI}}
      visualStudioBootstrapperURI: ${{parameters.bootstrapperUrl}}
      visualStudioSigning: Test
      testMachineConfigurationJobTimeoutInMinutes: 30
      testMachineConfigurationJobDisplayName: 'Apex Test Machine Configuration'
      testExecutionJobDisplayName: 'Apex Test Execution'
      testExecutionJobTimeoutInMinutes: ${{parameters.testExecutionJobTimeoutInMinutes}}
      testDeploymentCleanupMode: ${{parameters.testDeploymentCleanupMode}}
      testMachineConfigurationJobVariables:
      - name: VisualStudio.InstallationUnderTest.BootstrapperBranch
        value: # The branch in the VS repo the bootstrapper was based on, e.g. "main"

##############################
## preOperationsSteps
##############################
      preOperationsSteps:
        - task: PowerShell@1
          displayName: "Print Environment Variables"
          inputs:
            scriptType: "inlineScript"
            inlineScript: |
              Get-ChildItem Env: | Sort-Object Name | Format-Table -Wrap -AutoSize

        - task: DownloadPipelineArtifact@2
          displayName: "Download scripts"
          inputs:
            artifactName: "scripts"
            downloadPath: "$(Build.StagingDirectory)/scripts"

        - task: PowerShell@1
          displayName: "SetupFunctionalTests.ps1"
          inputs:
            scriptName: "$(Build.StagingDirectory)/scripts/e2etests/SetupFunctionalTests.ps1"

