parameters:
- name: DartLabEnvironment
  displayName: DartLab Environment
  type: string
  default: Production
  values:
  - Production
  - Staging

- name: NuGetLocalizationType
  displayName: Whether to do production-ready localization (Full), or pseudo-localization, aka PLOC, (Pseudo) for testing.
  type: string
  default: Full
  values:
  - Full
  - Pseudo
- name: RunBuildForPublishing
  displayName: Build bits for publishing
  type: boolean
  default: false

resources:
  pipelines:
  - pipeline: DartLab
    source: DartLab
    branch: main
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DartLab.Templates
    ref: refs/heads/main

variables:
  BINLOG_DIRECTORY: $(Build.StagingDirectory)/binlog
  DOTNET_NOLOGO: 1
  NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY: 3,1000
  Codeql.Enabled: false
  Codeql.TSAEnabled: false
  RunBuildForPublishing: ${{ parameters.RunBuildForPublishing }}

stages:
- template: templates/pipeline.yml
  parameters:
    isOfficialBuild: false
    DartLabEnvironment: ${{parameters.DartLabEnvironment}}
    NuGetLocalizationType: ${{parameters.NuGetLocalizationType}}
    RunBuildForPublishing: ${{parameters.RunBuildForPublishing}}
