# No CI trigger rely on Pipeline trigger only
trigger: none

resources:
  pipelines:
    - pipeline: nugetclientofficial
      source: NuGet.Client-Official
      trigger:
        branches:
          - dev
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Unofficial.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES
      binskim:
        enabled: true
        scanOutputDirectoryOnly: true
      policheck:
        enabled: true
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\.gdn\.gdnsuppress
      tsa:
        enabled: true
    pool:
      name: AzurePipelines-EO
      image: VSEngSS-MicroBuild2022-1ES
      os: windows
    stages:
    - stage: compliance
      displayName: "Run Compliance Tasks"
      jobs:
      - job: Static_Analysis
        displayName: "Static Analysis"
        timeoutInMinutes: 180
        pool:
          name: VSEngSS-MicroBuild2022-1ES
        templateContext:
          inputs:
            - input: pipelineArtifact
              pipeline: nugetclientofficial
              artifactName: symbols - NonRTM
              targetPath: $(Pipeline.Workspace)\symbols\NonRTM

        steps:
        - task: APIScan@2
          displayName: Run APIScan
          inputs:
            softwareFolder: $(Pipeline.Workspace)\symbols
            softwareName: "NuGet.Client"
            softwareVersionNum: "$(Build.BuildId)"
            isLargeApp: true
            toolVersion: "Latest"
            azureSubscription: 'VSEng-APIScanSC'
          env:
            AzureServicesAuthConnectionString: RunAs=App;AppId=d318cba7-db4d-4fb3-99e1-01879cb74e91;TenantId=72f988bf-86f1-41af-91ab-2d7cd011db47;ServiceConnectionId=93e24264-c5e6-4681-8175-ec8a41668480;
            SYSTEM_ACCESSTOKEN: $(System.AccessToken)
