resources:
  pipelines:
    - pipeline: nugetclientofficial
      source: NuGet.Client-Official
      trigger:
        - dev

jobs:
  - job: Static Analysis
    pool:
      vmImage: windows-latest

    steps:

  - task: CredScan@2
    inputs:
      toolMajorVersion: "V2"

  - task: PoliCheck@1
    inputs:
      inputType: "Basic"
      targetType: "F"
      targetArgument: "$(Build.SourcesDirectory)"
      result: "PoliCheck.xml"

  - task: SdtReport@1
    displayName: "Generate Analysis Report"
    inputs:
      CredScan: true
      PoliCheck: true
      ToolLogsNotFoundAction: "Standard"

  - task: TSAUpload@1
    displayName: "Upload to TSA"
    inputs:
      tsaVersion: "TsaV2"
      codebase: "Existing"
      tsaEnvironment: "PROD"
      codeBaseName: "$(TsaCodebaseName)"
      notificationAlias: "$(TsaNotificationEmail)"
      notifyAlwaysV2: true
      codeBaseAdmins: "$(TsaCodebaseAdmins)"
      instanceUrlForTsaV2: "$(TsaInstanceUrl)"
      projectNameDEVDIV: "$(TsaProjectName)"
      areaPath: "$(TsaBugAreaPath)"
      iterationPath: "$(TsaIterationPath)"
      uploadAPIScan: false
      uploadBinSkim: false
      uploadCredScan: true
      uploadFortifySCA: false
      uploadFxCop: false
      uploadModernCop: false
      uploadPoliCheck: true
      uploadPREfast: false
      uploadRoslyn: false
      uploadTSLint: false
      uploadAsync: true

  ### Run latest version of APIScan listed at https://www.1eswiki.com/wiki/APIScan_Build_Task
  - task: APIScan@2
    displayName: Run APIScan
    inputs:
      softwareFolder: "$(Build.Repository.LocalPath)\\artifacts\\symbolstoindex"
      softwareName: 'NuGet.Client'
      softwareVersionNum: '$(Build.BuildId)'
      isLargeApp: true
      toolVersion: 'Latest'
    condition: and(succeeded(), ne(variables['DisableAPIScan'], 'true'))
    env:
      AzureServicesAuthConnectionString: runAs=App;AppId=$(ApiScanClientId);TenantId=$(ApiScanTenant);AppKey=$(ApiScanSecret)

  ### Publish Code Analysis results to build Artifacts.
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-publishsecurityanalysislogs.PublishSecurityAnalysisLogs@2
    displayName: 'Publish Code Analysis Logs'

  - task: PublishSecurityAnalysisLogs@2
    displayName: "Publish CodeAnalysis Logs"
    inputs:
      ArtifactName: "CodeAnalysisLogs"
      ArtifactType: "Container"
      AllTools: false
      AntiMalware: false
      APIScan: false
      BinSkim: false
      CodesignValidation: false
      CredScan: true
      FortifySCA: false
      FxCop: false
      ModernCop: false
      MSRD: false
      PoliCheck: true
      RoslynAnalyzers: false
      SDLNativeRules: false
      Semmle: false
      TSLint: false
      WebScout: false
      ToolLogsNotFoundAction: "Standard"
