# This is a pipeline that will run NuGet.Client's Visual Studio daily integration tests

pr: none
trigger:
  branches:
    include:
    - dev

parameters:
# build parameters
- name: NuGetLocalizationType
  displayName: Whether to do production-ready localization (Full), or pseudo-localization, aka PLOC, (Pseudo) for testing.
  type: string
  default: Full
  values:
  - Full
  - Pseudo

# Dartlab options
- name: DartLabEnvironment
  displayName: DartLab Environment
  type: string
  default: Production
  values:
  - Production
  - Staging
- name: ApexAgentCleanup
  displayName: Delete or keep VS Apex test machine for debugging
  type: string
  default: delete
  values:
  - delete
  - stop

resources:
  pipelines:
  - pipeline: DartLab
    source: DartLab
    branch: main
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DartLab.Templates
    ref: refs/heads/main

variables:
  DOTNET_NOLOGO: 1
  CI: true
  Codeql.Enabled: false

stages:
- stage: Build
  displayName: Build NuGet and tests
  jobs:
  - job: Build
    timeoutInMinutes: 170
    pool:
      name: VSEngSS-MicroBuild2022-1ES
    steps:
    - template: vs-test/build.yml
      parameters:
        NuGetLocalizationType: ${{ parameters.NuGetLocalizationType }}

# Dartlab's template defines this in its own stage
- template: vs-test/apex.yml
  parameters:
    condition: "and(succeeded(), ne(variables['RunApexTests'], 'false'))"
    dependsOn:
    - Build
    variables:
    - name: VsBootstrapperUrl
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.bootstrapperUrl']]
    - name: VsBaseBuildDrop
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.BaseBuildDrop']]
    - name: QBuildSessionId
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.QBuildSessionId']]
    - name: RunSettingsDrop
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.RunSettingsDrop']]
    baseBuildDrop: $(VsBaseBuildDrop)
    bootstrapperUrl: $(VsBootstrapperUrl)
    dartLabEnvironment: ${{parameters.DartLabEnvironment}}
    isOfficialBuild: false
    QBuildSessionId: $(QBuildSessionId)
    runSettingsURI: https://vsdrop.corp.microsoft.com/file/v1/$(RunSettingsDrop);NuGet.Tests.Apex.Daily.runsettings
    testExecutionJobTimeoutInMinutes: 150
    testMachineCleanUpStrategy: ${{parameters.ApexAgentCleanup}}
