pr: none
trigger:
  batch: false
  branches:
    include:
      - dev
      - release-*

# Weekly builds for supported branches, to maintain CI build health + keep OptProf training data fresh
# Generally this means LTS versions + current GA version
# Visual Studio support lifecycle: https://docs.microsoft.com/en-us/visualstudio/productinfo/vs-servicing
# .NET support lifecycle: https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
schedules:
- cron: "0 10 * * 0" # Every sunday at 10am UTC
  displayName: Weekly branch build
  branches:
    include:
      - release-5.11.x # VS 16.11 and .NET 5 SDK 5.0.4xx
      - release-6.0.x # VS 17.0 and .NET 6 SDK 6.0.1xx
      - release-6.1.x # VS 17.1 and .NET 6 SDK 6.0.2xx
  always: true

parameters:
- name: DartLabEnvironment
  displayName: DartLab Environment
  type: string
  default: Production
  values:
  - Production
  - Staging
- name: E2EPart1AgentCleanup
  displayName: Delete or keep E2E Part 1 machine for debugging
  type: string
  default: delete
  values:
  - delete
  - stop
- name: E2EPart2AgentCleanup
  displayName: Delete or keep E2E Part 2 machine for debugging
  type: string
  default: delete
  values:
  - delete
  - stop
- name: ApexAgentCleanup
  displayName: Delete or keep VS Apex test machine for debugging
  type: string
  default: delete
  values:
  - delete
  - stop

extends:
  template: templates/pipeline.yml
  parameters:
    isOfficialBuild: true
    DartLabEnvironment: ${{parameters.DartLabEnvironment}}
    E2EPart1AgentCleanup: ${{parameters.E2EPart1AgentCleanup}}
    E2EPart2AgentCleanup: ${{parameters.E2EPart2AgentCleanup}}
    ApexAgentCleanup: ${{parameters.ApexAgentCleanup}}
