parameters:
- name: RunBuildForPublishing
  displayName: Build bits for publishing
  type: boolean
  default: true
- name: RunCrossFrameworkTestsOnWindows
  displayName: Run cross framweork tests on Windows
  type: boolean
  default: true
- name: RunEndToEndTests
  displayName: Run end-to-end tests
  type: boolean
  default: true
- name: RunFunctionalTestsOnWindows
  displayName: Run functional tests on Windows
  type: boolean
  default: true
- name: RunSourceBuild
  displayName: Run source build
  type: boolean
  default: true
- name: RunTestsOnLinux
  displayName: Run tests on Linux
  type: boolean
  default: true
- name: RunTestsOnMac
  displayName: Run tests on Mac
  type: boolean
  default: true
- name: RunMonoTestsOnMac
  displayName: Run Mono tests on Mac
  type: boolean
  default: true

resources:
  pipelines:
  - pipeline: DartLab
    source: DartLab
    branch: main
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DartLab.Templates
    ref: refs/heads/main

variables:
  BINLOG_DIRECTORY: $(Build.StagingDirectory)/binlog
  DOTNET_NOLOGO: 1
  NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY: 3,1000
  Codeql.Enabled: false
  Codeql.TSAEnabled: false
  RunBuildForPublishing: ${{ parameters.RunBuildForPublishing }}
  RunCrossFrameworkTestsOnWindows: ${{ parameters.RunCrossFrameworkTestsOnWindows }}
  RunFunctionalTestsOnWindows: ${{ parameters.RunFunctionalTestsOnWindows }}
  RunSourceBuild: ${{ parameters.RunSourceBuild }}
  RunTestsOnLinux: ${{ parameters.RunTestsOnLinux }}
  RunTestsOnMac: ${{ parameters.RunTestsOnMac }}
  RunMonoTestsOnMac: ${{ parameters.RunMonoTestsOnMac }}

stages:
- template: templates/pipeline.yml
  parameters:
    isOfficialBuild: true
    DartLabEnvironment: ${{parameters.DartLabEnvironment}}
    NuGetLocalizationType: Full
    RunBuildForPublishing: ${{parameters.RunBuildForPublishing}}
    RunCrossFrameworkTestsOnWindows: ${{parameters.RunCrossFrameworkTestsOnWindows}}
    RunFunctionalTestsOnWindows: ${{parameters.RunFunctionalTestsOnWindows}}
    RunSourceBuild: ${{parameters.RunSourceBuild}}
    RunTestsOnLinux: ${{parameters.RunTestsOnLinux}}
    RunTestsOnMac: ${{parameters.RunTestsOnMac}}
    RunMonoTestsOnMac: ${{parameters.RunMonoTestsOnMac}}
