# NuGet OptProf profiling pipeline

trigger: none # Prevents this pipeline from triggering on check-ins

resources:
  pipelines:
  - pipeline: ComponentBuildUnderTest
    source: NuGet.Client-Official
  - pipeline: DartLab
    source: DartLab
    branch: main
  - pipeline: DartLab.OptProf
    source: DartLab.OptProf
    branch: dev/mityler/VsSigning
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DartLab.Templates
    ref: refs/heads/main
  - repository: DartLabOptProfTemplates
    type: git
    name: DartLab.OptProf
    ref: refs/heads/dev/mityler/VsSigning

parameters:
# The prefix naming of the OptimizationInputs drop
# NOTE: fix prefix when ready for production (remove 'TEST')
- name: optimizationDropPrefix
  type: string
  default: TESTOptimizationInputs/$(System.TeamProject)/$(Build.Repository.Name)

# Whether or not to delete the test machines after the run completes.
- name: testMachineCleanUpStrategy
  type: string
  default: delete
  values:
  - delete
  - stop

stages:
- template: \templates\stages\visual-studio\single-runsettings.yml@DartLabOptProfTemplates
  parameters:
    ##### Required #####
    runSettingsURI: https://vsdrop.corp.microsoft.com/file/v1/RunSettings/$(System.TeamProject)/$(Build.Repository.Name)/dev/$(resources.pipeline.ComponentBuildUnderTest.runID);NuGet.OptProfV2.runsettings
    visualStudioBootstrapperURI: $(VisualStudio.InstallationUnderTest.BootstrapperURL)
    ##### Optional #####
    name: OptProf_ProfilingWorkflow
    displayName: OptProf Profiling Workflow
    optOptimizationInputsDropName: ${{parameters.optimizationDropPrefix}}/$(resources.pipeline.ComponentBuildUnderTest.sourceCommit)/$(Build.BuildId)/$(System.StageId)/$(System.StageAttempt)
    # Remove this parameter if you don't want LKG support
    previousOptimizationInputsDropName: $(PreviousOptimizationInputsDropName)
    testLabPoolName: VS-Platform
    testMachineCleanUpStrategy: ${{parameters.testMachineCleanUpStrategy}}
    visualStudioSigning: Test
    ##### Step Hooks #####
    preTestMachineConfigurationStepList:
    - powershell: |
        try {
          Write-Host "Set VSBranch variable"
          $buildInfoJsonFilePath = "$(Pipeline.Workspace)\ComponentBuildUnderTest\BuildInfo\buildinfo.json"

          Write-Host "buildinfo.json drop URI:  $buildInfoJsonFilePath"
          $buildInfoJson = (Get-Content $buildInfoJsonFilePath -Raw) | ConvertFrom-Json
          $VSBranch = $buildInfoJson.VsTargetBranch

          Write-Host "Target Visual Studio branch (full name): $VSBranch"

          # The value will be something like 'master' or 'rel/d16.4';
          # however, the subsequent task which gets bootstrapper details has a parameter (VSBranch)
          # which (as of writing this) requires the branch "short" name.
          # For the 'master' branch, the short name is still 'master'.
          # For the 'rel/d16.4' branch, the short name is 'd16.4'.
          # Ideally, we would not need to figure out the branch short name ourselves,
          # but short-term we will to unblock ourselves.
          $branchParts = $VSBranch.Split('/')
          $VSBranch = $branchParts[$branchParts.Count - 1]

          Write-Host "Target Visual Studio branch (short name): $VSBranch"

          Write-Host "Target Visual Studio branch: $VSBranch"
          Set-AzurePipelinesVariable 'VSBranch' $VSBranch
        }
        catch {
          Write-Host $_
          Write-Error "Failed to set VSBranch pipeline variable"
          throw
        }
      displayName: 'Set VSBranch variable'
    - powershell : |
        try {
          $branchName = "$(resources.pipeline.ComponentBuildUnderTest.sourceBranch)"
          $branchName = $branchName.Replace('refs/heads/', '')

          Write-Host "RunSettingsURI: https://vsdrop.corp.microsoft.com/file/v1/RunSettings/$(System.TeamProject)/$(Build.Repository.Name)/$branchName/$(resources.pipeline.ComponentBuildUnderTest.runID);NuGet.OptProfV2.runsettings"
          Set-AzurePipelinesVariable 'RunSettingsURI' "https://vsdrop.corp.microsoft.com/file/v1/RunSettings/$(System.TeamProject)/$(Build.Repository.Name)/$branchName/$(resources.pipeline.ComponentBuildUnderTest.runID);NuGet.OptProfV2.runsettings"
        }
        catch {
          Write-Host $_
          Write-Error "Failed to set SourceBranchName pipeline variable"
          throw
        }
      displayName: 'Set RunSettingsURI variable'
    - download: ComponentBuildUnderTest
      artifact: MicroBuildOutputs
      patterns: '**\BootstrapperInfo.json'
      displayName: Download Bootstrapper Information
    - task: PowerShell@2
      displayName: Set 'VisualStudio.InstallationUnderTest.BootstrapperURL'
      inputs:
        filePath: $(DartLab.Path)\Scripts\VisualStudio\Bootstrapper\Get-BootstrapperURL.ps1
        arguments: -BootstrapperInfoJsonURI '$(Pipeline.Workspace)\ComponentBuildUnderTest\MicroBuildOutputs\BootstrapperInfo.json' -VSBranch '$(VSBranch)' -OutVariableName 'VisualStudio.InstallationUnderTest.BootstrapperURL'
    preDeployAndRunTestsStepList:
    - download: ComponentBuildUnderTest
    # Remove this step hook and it's task if you don't want LKG support
    prePublishOptimizationInputsDropStepList:
    # Set parameter for PreviousOptimizationInputsDropName 
    - powershell: |
        try {
          $artifactName = 'OptProf'
          $BuildID = $(resources.pipeline.ComponentBuildUnderTest.runID)
          $artifact = Get-BuildArtifact -InstanceURL 'https://dev.azure.com/devdiv' -ProjectName 'DevDiv' -BuildID $BuildID -ArtifactName $artifactName -OAuthAccessToken (ConvertTo-SecureString '$(System.AccessToken)' -AsPlainText -Force)
          $containerName = $artifact.Resource.Data -Split '/' | Select-Object -Last 1
          $fileName = Join-Path $containerName 'Metadata.json'
          $jsonString = Read-BuildArtifactFile -InstanceURL 'https://dev.azure.com/devdiv' -ProjectName 'DevDiv' -BuildID $BuildID -ArtifactName $artifactName -FileName $fileName -OAuthAccessToken (ConvertTo-SecureString '$(System.AccessToken)' -AsPlainText -Force)
          $json = $jsonString | ConvertFrom-Json

          Write-Host "The content of the metadata.json file was $json"

          $dropname = $json.OptimizationData
          $commitID = $json.CommitID
          
          Write-Host "PreviousOptimizationInputsDropName: $dropname"
          Set-AzurePipelinesVariable 'PreviousOptimizationInputsDropName' $dropname
        }
        catch {
          Write-Host $_
          Write-Error "Failed to set OptimizationInputsDropName pipeline variable"
          throw
        }
      displayName: Set PreviousOptimizationInputsDropName