# NuGet OptProf profiling pipeline

trigger: none # Prevents this pipeline from triggering on check-ins

resources:
  pipelines:
  - pipeline: ComponentBuildUnderTest
    source: NuGet.Client-Official
  - pipeline: DartLab
    source: DartLab
    branch: main
  - pipeline: DartLab.OptProf
    source: DartLab.OptProf
    branch: dev/mityler/VsSigning
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DartLab.Templates
    ref: refs/heads/main
  - repository: DartLabOptProfTemplates
    type: git
    name: DartLab.OptProf
    ref: refs/heads/dev/mityler/VsSigning

parameters:
# The name of the Visual Studio branch the bootstrapper URL was built from
- name: vsBranch
  type: string
  default: main

# The prefix naming of the OptimizationInputs drop
# NOTE: fix prefix when ready for production (remove 'TEST')
- name: optimizationDropPrefix
  type: string
  default: TESTOptimizationInputs/$(System.TeamProject)/$(Build.Repository.Name)

# Whether or not to delete the test machines after the run completes.
- name: testMachineCleanUpStrategy
  type: string
  default: delete
  values:
  - delete
  - stop

stages:
- template: \templates\stages\visual-studio\single-runsettings.yml@DartLabOptProfTemplates
  parameters:
    ##### Required #####
    runSettingsURI: $(RunSettingsURI)
    visualStudioBootstrapperURI: $(VisualStudio.InstallationUnderTest.BootstrapperURL)
    ##### Optional #####
    name: OptProf_ProfilingWorkflow
    displayName: OptProf Profiling Workflow
    optOptimizationInputsDropName: ${{parameters.optimizationDropPrefix}}/$(resources.pipeline.ComponentBuildUnderTest.sourceCommit)/$(Build.BuildId)/$(System.StageId)/$(System.StageAttempt)
    # Remove this parameter if you don't want LKG support
    previousOptimizationInputsDropName: $(PreviousOptimizationInputsDropName)
    testLabPoolName: VS-Platform
    testMachineCleanUpStrategy: ${{parameters.testMachineCleanUpStrategy}}
    visualStudioSigning: Test
    ##### Step Hooks #####
    preTestMachineConfigurationStepList:
    - powershell : |
        try {
          $branchName = "$(resources.pipeline.ComponentBuildUnderTest.sourceBranch)"
          $branchName = $branchName.Replace('refs/heads/', '')

          Write-Host "RunSettingsURI: https://vsdrop.corp.microsoft.com/file/v1/RunSettings/$(System.TeamProject)/$(Build.Repository.Name)/$branchName/$(resources.pipeline.ComponentBuildUnderTest.runID);NuGet.OptProfV2.runsettings"
          Set-AzurePipelinesVariable 'RunSettingsURI' https://vsdrop.corp.microsoft.com/file/v1/RunSettings/$(System.TeamProject)/$(Build.Repository.Name)/$branchName/$(resources.pipeline.ComponentBuildUnderTest.runID);NuGet.OptProfV2.runsettings
        }
        catch {
          Write-Host $_
          Write-Error "Failed to set SourceBranchName pipeline variable"
          throw
        }
      displayName: Set RunSettingsURI
    - download: ComponentBuildUnderTest
      artifact: MicroBuildOutputs
      patterns: '**\BootstrapperInfo.json'
      displayName: Download Bootstrapper Information
    - task: PowerShell@2
      displayName: Set 'VisualStudio.InstallationUnderTest.BootstrapperURL'
      inputs:
        filePath: $(DartLab.Path)\Scripts\VisualStudio\Bootstrapper\Get-BootstrapperURL.ps1
        arguments: -BootstrapperInfoJsonURI '$(Pipeline.Workspace)\ComponentBuildUnderTest\MicroBuildOutputs\BootstrapperInfo.json' -VSBranch '${{parameters.vsBranch}}' -OutVariableName 'VisualStudio.InstallationUnderTest.BootstrapperURL'
    preDeployAndRunTestsStepList:
    - download: ComponentBuildUnderTest
    # Remove this step hook and it's task if you don't want LKG support
    prePublishOptimizationInputsDropStepList:
    # Set parameter for PreviousOptimizationInputsDropName 
    - powershell: |
        try {
          $artifactName = 'OptProf'
          $BuildID = $(resources.pipeline.ComponentBuildUnderTest.runID)
          $artifact = Get-BuildArtifact -InstanceURL 'https://dev.azure.com/devdiv' -ProjectName 'DevDiv' -BuildID $BuildID -ArtifactName $artifactName -OAuthAccessToken (ConvertTo-SecureString '$(System.AccessToken)' -AsPlainText -Force)
          $containerName = $artifact.Resource.Data -Split '/' | Select-Object -Last 1
          $fileName = Join-Path $containerName 'Metadata.json'
          $jsonString = Read-BuildArtifactFile -InstanceURL 'https://dev.azure.com/devdiv' -ProjectName 'DevDiv' -BuildID $BuildID -ArtifactName $artifactName -FileName $fileName -OAuthAccessToken (ConvertTo-SecureString '$(System.AccessToken)' -AsPlainText -Force)
          $json = $jsonString | ConvertFrom-Json

          Write-Host "The content of the metadata.json file was $json"

          $dropname = $json.OptimizationData
          $commitID = $json.CommitID
          
          Write-Host "PreviousOptimizationInputsDropName: $dropname"
          Set-AzurePipelinesVariable 'PreviousOptimizationInputsDropName' $dropname
        }
        catch {
          Write-Host $_
          Write-Error "Failed to set OptimizationInputsDropName pipeline variable"
          throw
        }
      displayName: Set PreviousOptimizationInputsDropName