parameters:
- name: RunUnitTestsOnWindows
  displayName: 'Run unit tests on Windows'
  type: boolean
  default: true
- name: RunFunctionalTestsOnWindows
  displayName: Run functional tests on Windows
  type: boolean
  default: true
- name: RunUnitTestsOnLinux
  displayName: 'Run unit tests on Linux'
  type: boolean
  default: false
- name: RunFunctionalTestsOnLinux
  displayName: Run functional tests on Linux
  type: boolean
  default: false

variables:
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Debug'
  BINLOG_DIRECTORY: $(Build.StagingDirectory)/binlog
  DOTNET_NOLOGO: 1
  NUGET_EXPERIMENTAL_CHAIN_BUILD_RETRY_POLICY: 3,1000
  RunUnitTestsOnWindows: ${{ parameters.RunUnitTestsOnWindows }}
  RunFunctionalTestsOnWindows: ${{ parameters.RunFunctionalTestsOnWindows }}

jobs:
- ${{ if eq(parameters.RunUnitTestsOnWindows, true) }}:
  - template: pull_request.job.yml
    parameters:
      name: UnitTestsWindows
      displayName: 'Run Unit Tests on Windows'
      osName: Windows
      vmImage: windows-latest
      testType: Unit

- ${{ if eq(parameters.RunFunctionalTestsOnWindows, true) }}:
  - template: pull_request.job.yml
    parameters:
      name: FunctionalTestsWindows
      displayName: 'Run Functional Tests on Windows'
      osName: Windows
      vmImage: windows-latest
      testType: Functional

- ${{ if eq(parameters.RunUnitTestsOnLinux, true) }}:
  - template: pull_request.job.yml
    parameters:
      name: UnitTestsLinux
      displayName: 'Run Unit Tests on Linux'
      osName: Linux
      vmImage: ubuntu-latest
      testType: Unit

- ${{ if eq(parameters.RunFunctionalTestsOnLinux, true) }}:
  - template: pull_request.job.yml
    parameters:
      name: FunctionalTestsLinux
      displayName: 'Run Functional Tests on Linux'
      osName: Linux
      vmImage: ubuntu-latest
      testType: Functional
