# This is a pipeline that will run NuGet.Client's Visual Studio integration tests

pr: none
trigger:
  branches:
    include:
    - dev-*

parameters:
# Specific tests
- name: RunApexTests
  displayName: Run Apex tests
  type: boolean
  default: true
- name: RunEndToEndTests
  displayName: Run end-to-end tests
  type: boolean
  default: true
- name: EnableApexBlameHangDumpCollector
  displayName: Collect Apex hang dumps (aborts the test run on timeout)
  type: boolean
  default: false

# Dartlab options
- name: DartLabEnvironment
  displayName: DartLab Environment
  type: string
  default: Production
  values:
  - Production
  - Staging
- name: testMachineHoldStrategy
  displayName: Hold E2E test machine for debugging
  type: string
  default: None
  values:
  - None
  - Completion
  - Execution
  - Failure
  - Timeout
- name: ApexAgentCleanup
  displayName: Cleanup VS Apex test machine
  type: string
  default: Always
  values:
    - Always
    - Never
    - OnSuccess

resources:
  pipelines:
  - pipeline: DartLab
    source: DartLab
    branch: refs/heads/main
    tags:
    - Production
  repositories:
  # DartLab1ES/CloudTest templates repository
  - repository: DartLabTemplates
    type: git
    name: DevDiv/DartLab
    ref: refs/tags/Production

variables:
  DOTNET_NOLOGO: 1
  CI: true
  Codeql.Enabled: false
  SourceBranch: $[replace(variables['Build.SourceBranch'], 'refs/heads/', '')]

stages:
- stage: Build
  displayName: Build NuGet and tests
  jobs:
  - job: Build
    timeoutInMinutes: 170
    pool:
      name: VSEng-MicroBuildVSStable
    steps:
    - template: vs-test/build.yml
      parameters:
        enableApexBlameHangDumpCollector: ${{parameters.EnableApexBlameHangDumpCollector}}

- template: vs-test/end_to_end.yml
  parameters:
    stageName: VS_EndToEnd
    stageDisplayName: On Windows
    condition: "and(succeeded(), ne(variables['RunEndToEndTests'], 'false'))"
    dependsOn:
    - Build
    variables:
    - name: VsBootstrapperUrl
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.bootstrapperUrl']]
    - name: RunSettingsDrop
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.RunSettingsDrop']]
    bootstrapperUrl: $(VsBootstrapperUrl)
    DartLabEnvironment: ${{parameters.DartLabEnvironment}}
    runSettingsURI: https://vsdrop.corp.microsoft.com/file/v1/$(RunSettingsDrop);NuGet.Tests.Apex.runsettings
    testExecutionJobTimeoutInMinutes: 412 # cloud test minimum
    testMachineHoldStrategy: ${{parameters.testMachineHoldStrategy}}

# Dartlab's template defines this in its own stage
- template: vs-test/apex.yml
  parameters:
    condition: "and(succeeded(), ne(variables['RunApexTests'], 'false'))"
    dependsOn:
    - Build
    variables:
    - name: bootstrapperUrl
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.bootstrapperUrl']]
    - name: RunSettingsDrop
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.RunSettingsDrop']]
    - name: VsBootstrapperBranch
      value: $[stageDependencies.Build.Build.outputs['dartlab_variables.VsBootstrapperBranch']]
    bootstrapperUrl: $(bootstrapperUrl)
    runSettingsURI: https://vsdrop.corp.microsoft.com/file/v1/$(RunSettingsDrop);NuGet.Tests.Apex.runsettings
    testExecutionJobTimeoutInMinutes: 412 # cloud test minimum
    testMachineTotalCount: '2'
    testCaseDistributionBatchingStrategy: OptimizeDurationForPerformance
    testDeploymentCleanupMode: ${{parameters.ApexAgentCleanup}}
    VsBootstrapperBranch: $(VsBootstrapperBranch)
