// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// Do not manually edit this autogenerated file:
// instead modify the neighboring .tt file (text template) and/or NuGet.CommandLine.Xplat\Commands\Commands.xml (data file),
// then re-execute the text template via "run custom tool" on VS context menu for .tt file, or via dotnet-t4 global tool.

namespace NuGet.Commands
{
    public partial class PushArgs
    {
        public bool ForceEnglishOutput { get; set; }
        public string Source { get; set; }
        public string SymbolSource { get; set; }
        public int Timeout { get; set; }
        public string ApiKey { get; set; }
        public string SymbolApiKey { get; set; }
        public bool DisableBuffering { get; set; }
        public bool NoSymbols { get; set; }
        public string PackagePaths { get; set; }
        public bool NoServiceEndpoint { get; set; }
        public bool Interactive { get; set; }
        public bool SkipDuplicate { get; set; }
    }

}
