// Copyright (c) .NET Foundation. All rights reserved.
// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.VisualStudio.Threading.Analyzers", "VSTHRD010", Justification = "Test code does not need to follow this rule.")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.SolutionUpToDateCheckerTests.CreateRestoreSummary(NuGet.ProjectModel.PackageSpec,System.Boolean,System.Boolean)~NuGet.Commands.RestoreSummary")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.SolutionUpToDateCheckerTests.GetUniqueNames(NuGet.ProjectModel.PackageSpec[])~System.Collections.Generic.List{System.String}")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.SolutionUpToDateCheckerTests.PerformUpToDateCheck_WhenAProjectIsUnloaded_ItsWarningsAreNotReplayed")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.VsSolutionRestoreServiceTests.CreateDefaultIProjectSystemCacheMock(System.String)~Moq.Mock{NuGet.VisualStudio.IProjectSystemCache}")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.VsSolutionRestoreServiceTests.CreateDefaultISolutionRestoreWorkerMock~Moq.Mock{NuGet.VisualStudio.ISolutionRestoreWorker}")]
[assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.VsSolutionRestoreServiceTests.Dispose")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.VsSolutionRestoreServiceTests.NominateProjectAsync_CacheFilePathInPackageSpec_Succeeds(System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.VsSolutionRestoreServiceTests.NominateProjectAsync_WithRestoreAdditionalSourcesAndFallbackFolders(System.String,System.String,System.String,System.String,System.Boolean)~System.Threading.Tasks.Task")]
[assembly: SuppressMessage("Performance", "CA1825:Avoid zero-length array allocations", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.SolutionRestoreManager.Test.VsSolutionRestoreServiceTests.ToPackageSpec_CentralVersions_AreNotAddedToThePackageSpecIfCPVMIsNotEnabled(System.String,System.String)")]
