// <auto-generated />
namespace NuGet.ProjectModel
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Strings
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("NuGet.ProjectModel.Strings", typeof(Strings).GetTypeInfo().Assembly);

        /// <summary>
        /// Error loading lock file: {0}
        /// </summary>
        internal static string Log_ErrorReadingLockFile
        {
            get { return GetString("Log_ErrorReadingLockFile"); }
        }

        /// <summary>
        /// Error loading lock file: {0}
        /// </summary>
        internal static string FormatLog_ErrorReadingLockFile(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("Log_ErrorReadingLockFile"), p0);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}
