<?xml version="1.0" encoding="utf-8" standalone="no"?>
<Project ToolsVersion="14.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <RestoreSuccess Condition=" '$(RestoreSuccess)' == '' ">True</RestoreSuccess>
    <RestoreTool Condition=" '$(RestoreTool)' == '' ">NuGet</RestoreTool>
    <ProjectAssetsFile Condition=" '$(ProjectAssetsFile)' == '' ">$(MSBuildThisFileDirectory)project.assets.json</ProjectAssetsFile>
    <NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">N:\nuget\NuGet.Client\.test\work\768f5202\160a2ee4\globalPackages</NuGetPackageRoot>
    <NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">N:\nuget\NuGet.Client\.test\work\768f5202\160a2ee4\globalPackages;N:\nuget\NuGet.Client\.test\work\768f5202\160a2ee4\fallback</NuGetPackageFolders>
    <NuGetProjectStyle Condition=" '$(NuGetProjectStyle)' == '' ">PackageReference</NuGetProjectStyle>
    <NuGetToolVersion Condition=" '$(NuGetToolVersion)' == '' ">6.13.0</NuGetToolVersion>
  </PropertyGroup>
  <ItemGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <SourceRoot Include="N:\nuget\NuGet.Client\.test\work\768f5202\160a2ee4\globalPackages\" />
    <SourceRoot Include="N:\nuget\NuGet.Client\.test\work\768f5202\160a2ee4\fallback\" />
  </ItemGroup>
  <PropertyGroup Condition=" '$(ExcludeRestorePackageImports)' != 'true' ">
    <PkgNewtonsoft_Json Condition=" '$(PkgNewtonsoft_Json)' == '' ">N:\nuget\NuGet.Client\.test\work\768f5202\160a2ee4\globalPackages\newtonsoft.json\10.0.2</PkgNewtonsoft_Json>
  </PropertyGroup>
</Project>
