parameters:
  - name: stageName
    type: string
  - name: stageDisplayName
    type: string
  - name: dependsOn
    type: object
  - name: bootstrapperUrl
    type: string
  - name: runSettingsURI
    type: string
  - name: DartLabEnvironment
    type: string
  - name: condition
    type: string
  - name: variables
    type: object
  - name: testExecutionJobTimeoutInMinutes
    type: number
  - name: testMachineCleanUpStrategy
    type: string
    default: delete
    values:
      - delete
      - stop

stages:
  - template: stages\visual-studio\single-runsettings.yml@DartLabTemplates
    parameters:
      name: ${{parameters.stageName}}
      displayName: ${{parameters.stageDisplayName}}
      condition: ${{parameters.condition}}
      dependsOn: ${{parameters.dependsOn}}
      variables:
        - name: bootstrapperUrl
          value: ${{parameters.bootstrapperUrl}}
        - ${{parameters.variables}}
      runSettingsURI: ${{parameters.runSettingsURI}}
      visualStudioBootstrapperURI: $(bootstrapperUrl)
      testLabPoolName: VS-Platform
      dartLabEnvironment: ${{parameters.DartLabEnvironment}}
      visualStudioSigning: Test
      testExecutionJobTimeoutInMinutes: 150
      testMachineCleanUpStrategy: ${{parameters.testMachineCleanUpStrategy}}
      testAgentElevated: true
      preDeployAndRunTestsStepList:
        - task: PowerShell@1
          displayName: "Print Environment Variables"
          inputs:
            scriptType: "inlineScript"
            inlineScript: |
              Get-ChildItem Env: | Sort-Object Name | Format-Table -Wrap -AutoSize

        - task: DownloadBuildArtifacts@0
          displayName: "Download Build artifacts"
          inputs:
            artifactName: "VS15"
            downloadPath: "$(Build.Repository.LocalPath)/artifacts"

        - powershell: |
            $zipPath = "$(Build.Repository.Localpath)/artifacts/VS15/EndToEnd.zip"
            $dest = "$(System.DefaultWorkingDirectory)/artifacts/EndToEnd/"
            Write-Output "Extracting '$zipPath' to '$dest'"
            Expand-Archive -Path "$zipPath" -DestinationPath "$dest"
          displayName: "Extract EndToEnd.zip"

        - task: PowerShell@1
          displayName: "SetupFunctionalTests.ps1"
          inputs:
            scriptName: "$(System.DefaultWorkingDirectory)/artifacts/EndToEnd/scripts/SetupFunctionalTests.ps1"
