
parameters:
- name: isOfficialBuild
  type: boolean
  default: false
- name: DartLabEnvironment
  displayName: DartLab Environment
  type: string
  default: Production
  values:
  - Production
  - Staging
- name: ApexAgentCleanup
  displayName: Delete or keep VS Apex test machine for debugging
  type: string
  default: delete
  values:
  - delete
  - stop
- name: NuGetLocalizationType
  displayName: Whether to do production-ready localization (Full), or pseudo-localization, aka PLOC, (Pseudo) for testing.
  type: string
  default: Full
  values:
  - Full
  - Pseudo

resources:
  pipelines:
  - pipeline: DartLab
    source: DartLab
    branch: main
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DartLab.Templates
    ref: refs/heads/main

variables:
  DOTNET_NOLOGO: 1
  Codeql.Enabled: ${{ parameters.isOfficialBuild }}
  Codeql.TSAEnabled: ${{ parameters.isOfficialBuild }}

stages:

# Dartlab's template defines this in its own stage
- template: Apex_Tests_On_Windows_Daily.yml
  parameters:
    condition: "succeeded()"
    isOfficialBuild: ${{parameters.isOfficialBuild}}
    dartLabEnvironment: ${{parameters.DartLabEnvironment}}
    testExecutionJobTimeoutInMinutes: 150
    testMachineCleanUpStrategy: ${{parameters.ApexAgentCleanup}}
