parameters:
- name: isOfficialBuild
  type: boolean
  default: false
- name: RunBuildForPublishing
  displayName: Build bits for publishing
  type: boolean
  default: true
- name: SigningType
  displayName: Type of signing to use
  type: string
  values:
  - Real
  - Test

stages:
- stage: Initialize
  jobs:
  - job: GetSemanticVersion
    displayName: Get NuGet.Client semantic version
    timeoutInMinutes: 10
    pool:
      name: VSEng-MicroBuildVSLegacy
      demands: ImageOverride -equals server2025-microbuildVS2019-1es
      os: windows
    steps:
    - template: /eng/pipelines/templates/Initialize_Build_SemanticVersion.yml@self

  - job: Initialize_Build
    dependsOn: GetSemanticVersion
    timeoutInMinutes: 10
    variables:
      SemanticVersion: $[dependencies.GetSemanticVersion.outputs['setsemanticversion.SemanticVersion']]
      BuildRevision: $[counter(format('{0}.{1}', variables['SemanticVersion'], variables['build.definitionname']), 1)]
    pool:
      name: VSEng-MicroBuildVSLegacy
      demands: ImageOverride -equals server2025-microbuildVS2019-1es
      os: windows
    steps:
    - template: /eng/pipelines/templates/Initialize_Build.yml@self

- stage: Build_Insertable
  displayName: Build NuGet inserted into VS and .NET SDK
  dependsOn: Initialize
  jobs:
  - job: Build_and_UnitTest_NonRTM
    timeoutInMinutes: 170
    variables:
      BuildNumber: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.BuildNumber']]
      FullVstsBuildNumber: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.FullVstsBuildNumber']]
      isOfficialBuild: ${{ parameters.isOfficialBuild }}
      BuildRTM: "false"
    pool:
      name: VSEng-MicroBuildVSLegacy
      demands: ImageOverride -equals server2025-microbuildVS2019-1es
      os: windows
    templateContext:
      mb:
        localization:
          enabled: true
        signing:
          enabled: true
          signType: "${{ parameters.SigningType }}"
          ${{ if and(eq(parameters.isOfficialBuild, true), eq(parameters.SigningType, 'Real')) }}:
            signWithProd: true
        swix:
          enabled: true
        optprof:
          enabled: false
      outputs:
      - output: pipelineArtifact
        displayName: "Publish buildinfo.json as an artifact"
        condition: "succeeded()"
        targetPath: '$(Build.StagingDirectory)\BuildInfo'
        artifactName: "BuildInfo"

      - output: pipelineArtifact
        displayName: "Publish nupkgs"
        condition: "and(succeeded(), eq(variables['IsOfficialBuild'], 'true'))"
        targetPath: "$(Build.Repository.LocalPath)\\artifacts\\$(NupkgOutputDir)"
        artifactName: "nupkgs - $(RtmLabel)"

      - output: pipelineArtifact
        displayName: "Publish NuGet.exe VSIX and EndToEnd.zip as artifact"
        targetPath: "$(Build.Repository.LocalPath)\\artifacts\\$(VsixPublishDir)"
        artifactName: "$(VsixPublishDir)"

      - output: pipelineArtifact
        displayName: "Publish localizationArtifacts artifact"
        condition: "or(eq(variables['OverridePublishLocalizationArtifact'], 'true'), and(succeeded(), eq(variables['IsOfficialBuild'], 'true')))"
        targetPath: "$(Build.Repository.LocalPath)\\artifacts\\localizationArtifacts\\"
        artifactName: "localizationArtifacts"

      - output: pipelineArtifact
        displayName: "Publish symbols as pipeline artifacts"
        condition: "and(succeeded(), eq(variables['IsOfficialBuild'], 'true'))"
        targetPath: "$(Build.Repository.LocalPath)\\artifacts\\symbolstoindex"
        artifactName: "symbols - $(RtmLabel)"

      - output: artifactsDrop
        displayName: "Upload VSTS Drop"
        condition: "succeeded()"
        dropServiceURI: 'https://devdiv.artifacts.visualstudio.com'
        buildNumber: 'Products/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildNumber)'
        sourcePath: "$(Build.Repository.LocalPath)\\artifacts\\$(VsixPublishDir)"
        toLowerCase: false
        usePat: true
        dropMetadataContainerName: "DropMetadata-Product"

      - output: pipelineArtifact
        displayName: "LocValidation: Publish Logs as an artifact"
        condition: "succeeded()"
        artifactName: LocValidationLogs
        targetPath: "$(Build.Repository.LocalPath)\\logs\\LocalizationValidation"
        sbomEnabled: false

      - output: pipelineArtifact
        displayName: "Publish binlogs"
        condition: "or(failed(), eq(variables['System.debug'], 'true'))"
        artifactName: binlog - $(System.JobDisplayName) - Attempt $(System.JobAttempt)
        targetPath: $(Build.StagingDirectory)\binlog
        sbomEnabled: false
    steps:
    - template: /eng/pipelines/templates/Build_and_UnitTest.yml@self
      parameters:
        BuildRTM: false
        SigningType: ${{ parameters.SigningType }}

- stage: Build_For_Publishing
  displayName: Build NuGet published to nuget.org
  dependsOn: Initialize
  jobs:
  - job: Build_and_UnitTest_RTM
    condition: "and(succeeded(), ne(variables['RunBuildForPublishing'], 'false'))"
    timeoutInMinutes: 170
    variables:
      BuildNumber: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.BuildNumber']]
      FullVstsBuildNumber: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.FullVstsBuildNumber']]
      BuildRTM: "true"
    pool:
      name: VSEng-MicroBuildVSLegacy
      demands: ImageOverride -equals server2025-microbuildVS2019-1es
      os: windows
    templateContext:
      mb:
        localization:
          enabled: true
        signing:
          enabled: true
          signType: "${{ parameters.SigningType }}"
          ${{ if and(eq(parameters.isOfficialBuild, true), eq(parameters.SigningType, 'Real')) }}:
            signWithProd: true
        swix:
          enabled: true
        optprof:
          enabled: false
      outputs:
      - output: pipelineArtifact
        displayName: "Publish nupkgs"
        condition: "succeeded()"
        targetPath: "$(Build.Repository.LocalPath)\\artifacts\\$(NupkgOutputDir)"
        artifactName: "nupkgs - $(RtmLabel)"

      - output: pipelineArtifact
        displayName: "Publish NuGet.exe VSIX and EndToEnd.zip as artifact"
        targetPath: "$(Build.Repository.LocalPath)\\artifacts\\$(VsixPublishDir)"
        artifactName: "$(VsixPublishDir)"

      - output: pipelineArtifact
        displayName: "Publish symbols as pipeline artifacts"
        condition: "and(succeeded(), eq(variables['IsOfficialBuild'], 'true'))"
        targetPath: "$(Build.Repository.LocalPath)\\artifacts\\symbolstoindex"
        artifactName: "symbols - $(RtmLabel)"

      - output: pipelineArtifact
        displayName: "Publish binlogs"
        condition: "or(failed(), eq(variables['System.debug'], 'true'))"
        artifactName: binlog - $(System.JobDisplayName) - Attempt $(System.JobAttempt)
        targetPath: $(Build.StagingDirectory)\binlog
        sbomEnabled: false
    steps:
    - template: /eng/pipelines/templates/Build_and_UnitTest.yml@self
      parameters:
        BuildRTM: true
        SigningType: ${{ parameters.SigningType }}

# - stage: Tests
#   displayName: "Run Functional Tests"
#   dependsOn: Initialize
#   jobs:
#   - job: Functional_Tests_On_Windows
#     timeoutInMinutes: 120
#     variables:
#       BuildNumber: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.BuildNumber']]
#       FullVstsBuildNumber: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.FullVstsBuildNumber']]
#     condition: "and(succeeded(), eq(variables['RunFunctionalTestsOnWindows'], 'true'))"
#     pool:
#       name: VSEng-MicroBuildVSLegacy
#       demands: ImageOverride -equals server2025-microbuildVS2019-1es
#       os: windows
#     steps:
#     - template: /eng/pipelines/templates/Functional_Tests_On_Windows.yml@self
#
#   - job: Tests_On_Linux
#     timeoutInMinutes: 45
#     variables:
#       FULLVSTSBUILDNUMBER: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.FullVstsBuildNumber']]
#     condition: "and(succeeded(), eq(variables['RunTestsOnLinux'], 'true'))"
#     pool:
#       name: AzurePipelines-EO
#       image: 1ESPT-Ubuntu22.04
#       os: linux
#     steps:
#     - template: /eng/pipelines/templates/Tests_On_Linux.yml@self

# - stage: MacTests
#   displayName: "Mac Tests"
#   dependsOn:
#   - Initialize
#   - Build_Insertable
#   jobs:
#   - job: Tests_On_Mac
#     timeoutInMinutes: 75
#     variables:
#       FULLVSTSBUILDNUMBER: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.FullVstsBuildNumber']]
#     condition: "and(succeeded(), eq(variables['RunTestsOnMac'], 'true'))"
#     pool:
#       name: "Azure Pipelines"
#       vmImage: macos-latest
#       os: macOS
#     steps:
#     - template: /eng/pipelines/templates/Tests_On_Mac.yml@self

# - stage: End_To_End_Tests
#   displayName: "End To End Tests"
#   dependsOn:
#   - Initialize
#   - Build_Insertable
#   jobs:
#   - job: End_To_End_Tests_On_Windows
#     timeoutInMinutes: 100
#     variables:
#       FullVstsBuildNumber: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.FullVstsBuildNumber']]
#     condition: "and(succeeded(), eq(variables['RunEndToEndTests'], 'true'))"
#     pool:
#       name: VSEng-MicroBuildVSLegacy
#       demands: ImageOverride -equals server2025-microbuildVS2019-1es
#       os: windows
#     steps:
#     - template: /eng/pipelines/templates/End_To_End_Tests_On_Windows.yml@self

# - stage: Apex_Tests
#   displayName: "Apex Tests"
#   dependsOn:
#   - Initialize
#   - Build_Insertable
#   jobs:
#   - job: Apex_Tests_On_Windows
#     timeoutInMinutes: 120
#     variables:
#       BuildNumber: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.BuildNumber']]
#       FullVstsBuildNumber: $[stageDependencies.Initialize.Initialize_Build.outputs['updatebuildnumber.FullVstsBuildNumber']]
#     condition: "and(succeeded(), eq(variables['RunApexTests'], 'true'))"
#     pool:
#       name: VSEng-MicroBuildVSLegacy
#       demands: ImageOverride -equals server2025-microbuildVS2019-1es
#       os: windows
#     steps:
#     - template: /eng/pipelines/templates/Apex_Tests_On_Windows.yml@self
