// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "CA1816:Dispose methods should call SuppressFinalize", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.HashObjectWriterTests.Dispose")]
[assembly: SuppressMessage("Performance", "CA1826:Do not use Enumerable methods on indexable collections", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WithAssetTargetFallbackAndImportsValues_ReturnsValidAssetTargetFallbackFramework")]
[assembly: SuppressMessage("Performance", "CA1826:Do not use Enumerable methods on indexable collections", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.GetPackageSpec_WithAssetTargetFallbackAndWithSecondaryFrameworks_ReturnsTargetFrameworkInformationWithDualCompatibilityFramework")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.PackageSpecReader_PackOptions_Files1")]
[assembly: SuppressMessage("Performance", "CA1826:Do not use Enumerable methods on indexable collections", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.PackageSpecReader_PackOptions_Files1")]
[assembly: SuppressMessage("Performance", "CA1826:Do not use Enumerable methods on indexable collections", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.PackageSpecReader_PackOptions_Files2")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.JsonPackageSpecReaderTests.PackageSpecReader_PackOptions_Files2")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.LockFileFormatTests.LockFileFormat_ReadsFullErrorMessage")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.LockFileFormatTests.LockFileFormat_ReadsLockFileWithTools")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.LockFileFormatTests.LockFileFormat_ReadsLogMessageWithNoFilePath")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.LockFileFormatTests.LockFileFormat_ReadsLogMessageWithSameFilePathAndProjectPath")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.LockFileFormatTests.LockFileFormat_ReadsMinimalErrorMessage")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.LockFileFormatTests.LockFileFormat_ReadsMultipleMessages")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.LockFileFormatTests.LockFileFormat_ReadsWarningMessage")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.LockFileFormatTests.LockFileFormat_ReadsWarningMessageWithoutWarningLevel")]
[assembly: SuppressMessage("Performance", "CA1829:Use Length/Count property instead of Count() when available", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.LockFileFormatTests.LockFileFormat_SafeRead")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.LockFileLibraryTests.LockFileLibrary_EqualityDiffersOnMSBuildPath")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.LockFileLibraryTests.LockFileLibrary_EqualityEmpty")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.LockFileLibraryTests.LockFileLibrary_EqualitySameMSBuildPath")]
[assembly: SuppressMessage("Usage", "xUnit1004:Test methods should not be skipped", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.PackageSpecReferenceDependencyProviderTests.GetSpecDependencies_AddsCentralPackageVersionsIfDefined(System.Boolean)")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.PackageSpecTests.CreateBuildOptions~NuGet.ProjectModel.BuildOptions")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.PackageSpecTests.CreateIncludeExcludeFiles~NuGet.ProjectModel.IncludeExcludeFiles")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.PackageSpecTests.CreateProjectRestoreMetadata~NuGet.ProjectModel.ProjectRestoreMetadata")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.PackageSpecTests.CreateProjectRestoreSettings~NuGet.ProjectModel.ProjectRestoreSettings")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.ProjectRestoreMetadataTests.CreateProjectRestoreMetadata~NuGet.ProjectModel.ProjectRestoreMetadata")]
[assembly: SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "<Pending>", Scope = "member", Target = "~M:NuGet.ProjectModel.Test.TargetFrameworkInformationTests.CreateTargetFrameworkInformation(System.Collections.Generic.List{NuGet.LibraryModel.CentralPackageVersion})~NuGet.ProjectModel.TargetFrameworkInformation")]
